# Generated by Django 3.2.9 on 2021-11-22 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('M', 'Matutino'), ('V', 'Verspertino'), ('N', 'Noturno')], default='N', max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.student')),
            ],
        ),
    ]
